# -*- coding: utf-8 -*-
"""Clase-3.Secuencias Condicionales en Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IvLoRUNt1h-bWDCUx_kztZCzq530v6Zx

Sentencias Condicionales en Python

Operadores Relacionales
**>** mayor que

*   **< **menor que
*   **>=** mayor o igual que
*   **==** igual que
*   **!=** diferente a
*   **and** ambos deben ser iguales
*   **or** no de los dos debe ser verdadero
*   **in** texto inmerso en otro.
"""

usuario = input("Digite su usuario: " )
usu = "angie123"
if usuario == usu:
  print("El usuario es correcto")
else:
  print("Usuario incorrecto")

num = int(input("Digite el número "))
if num > 20:
  print("El numero es mayor a 20")
elif num > 15:
  print("El numero es mayor a 15")
elif num > 10:
  print("El numero es mayor a 10")
elif num > 5:
  print("El numero es mayor a 5")
else:
  print("El numero no cumple ninguna condición")

edad = int (input("Digite su edad "))
if edad >=13 and edad < 19:
  print("Eres un adolescente")
else:
  print("No es un adolescente")

palabra = input("Digite la palabra: ")
if palabra in "lina_catalina": 
  print("Verdadero")
else:
  print("Falso")

if "10" in "100":
  print("Verdadero")
else:
  print("Falso")

"""Se necesita un sistema para un supermercado, el cuál dará 10% de descuento a las personas que compren mas de $1000000 de lo contrario no dará ningún descuento, al cliente se le debe de dar el total a pagar. Condicional"""

compra = float(input("¿Cuanto fue el valor de la compra? "))
if compra > 1000000:
  descuento = compra * 0.10
  total = compra - descuento
  print ( "El descuento es", descuento, "y el valor total a pagar es", total)
  ##print ("El descuento es = ${:,.0f} y el total a pagar es = ${:,.0f}", format(descuento, total))
else:
  print("No tiene descuento porque su compra fue menor a 1000000")

"""Se necesita un sistema que reciba tres calificaciones parciales de un alumno y en base a estas darle su promedio donde si el promedio es menor a 3.0 se le dirá que está reprobado, en caso contrario el mensaje será aprobado."""

calificacion1 = float(input("Digite la calificacion 1: "))
calificacion2 = float(input("Digite la calificacion 2: "))
calificacion3 = float(input ("Digite la calificacion 3: "))
prom = round( (calificacion1 + calificacion2 + calificacion3)/3,2)

if prom < 3.0:
  estado = "Reprobado"
else:
  estado = "Aprobado"
print ( "El promedio es ", prom, "y el estado es ", estado)

"""**Taller 2**

Dando continuidad con el taller 1, el estudiante debe realizar las siguientes validaciones utilizando la sentencia condicional IF:
"""

numeroIdentificacion = 100000045
nombres = 'Angie'
apellido = 'Lara'
Direccion = 'Carrera 3 Sur'
Telefono = 3204000000
Edad = 60
Estado_civil = "soltera"
numeroHijos = 10
estatura = 1.50
FechaContratacion = 17042023
SueldoBasico = 1500001
diasLaborados = 10

print('Numero de identificacion es',numeroIdentificacion),
print('Nombre es', nombres),
print('Apellido es', apellido),
print('Direccion es', Direccion),
print('Telefono es', Telefono),
print('Edad es', Edad),
print('Estado civil es', Estado_civil),
print('Numero de hijos es', numeroHijos),
print('Estatura es',estatura),
print('Fecha de contratacion es', FechaContratacion),
print('El sueldo basico es', SueldoBasico),
print('Trabajo', diasLaborados, 'dias')

"""1. Si el empleado es mayor de 55 años disfrutará de un bono de prepensión correspondiente al 5% de su sueldo básico."""

if Edad > 55:
  bono = round(SueldoBasico * 0.05)
  total = SueldoBasico + bono
  print(" El empleado disfrutará de un bono de un valor de ", bono, "para un suelto total de ", total)
else:
  print("El empleado no tiene bonos disponibles para disfrutar ya que su edad es menor a 55")

"""2. Si el empleado es casado y tiene hijos se le otorgará un paseo cada diciembre."""

if Estado_civil in "casado" and numeroHijos > 0:
  print("El empleado tiene un paseo cada diciembre disponible")
else:
  print("El empleado no puede ir al paseo de diciembre")

"""3. Si el sueldo básico está entre 1000000 y 1500000 tendrá una comisión del 2% sobre el valor del sueldo. Si el sueldo básico está entre 1500001 y 2000000 tendrá una comisión del 5% sobre el valor del sueldo. Para todos los demás casos no habrá comisión."""

if SueldoBasico >= 1000000 and SueldoBasico <= 1500000:
  comision = round(SueldoBasico * 0.02)
  total = SueldoBasico + comision
  print(" El empleado tiene disponible una comision de ", comision, "su sueldo total a pagar es", total)
elif SueldoBasico >= 1500001 and SueldoBasico <= 2000000:
  comision = round(SueldoBasico * 0.05)
  total = SueldoBasico + comision
  print(" El empleado tiene disponible una comision de ", comision, "su sueldo total a pagar es", total)
else:
  print("El empleado no cumple con el valor de sueldo para recibir comision")

"""4. Si el empleado trabajó más de 20 días al mes y su sueldo es menor a 1000000 tendrá derecho a un bono de alimentación."""

if diasLaborados > 20 and SueldoBasico < 1000000:
  print("El empleado tiene derecho a reclamar un bono de alimentación")
else:
  print("El empleado no tiene derecho a bono de alimentación ya que solo trabajó", diasLaborados, "dias y su sueldo es", SueldoBasico)