# -*- coding: utf-8 -*-
"""Clase 4 -Ciclos repetitivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlFAnOEqcg63eJVwaqkRWHkWszEhXhSV

**CICLOS REPETITIVOS**

**Ciclo FOR**

Se utiliza para recorrer los elementos de un objeto iterable y ejecutar un bloque de código.
"""

for w in (1,2,3,4):
  print(w)

for w in "Angie":
  print(w)

"""**Función Range (start, stop, step)**

Cuando se pasa un parámetro a la función Range por default (stop)
"""

for i in range (6):
  print(i)

for i in range(0,11,2):
  print(i)

nombre = input("Digite su nombre: ")
for i in range(7):
  print(i, nombre)

"""Escribe un programa que realice la tabla de multiplicar de un número digitado por teclado."""

num = int(input("Digite el número de la tabla de multiplicar: "))
for i in range(11):
  print(i, "x", num, "=", num * i )

"""Escribe un programa que me sume los números pares del 0 al 10 y saque el total de la suma."""

# Variables acumuladoras
acu = 0
for i in range (0,11,2):
  acu = acu + i
  print (" El total de la suma de los numeros pares del 0 al 10 es", acu)

"""**Ciclo WHILE**

Repite un bloque de código mientras se cumpla una condición.
"""

x = 0
while x <= 10:
  print (x)
  x = x + 1

x = 0
while x <= 15:
  x = x + 3
  print(x)

resp = "si"
 while resp == "si" or resp == "SI" or resp == "sí" or resp == "Yes":
  a = 5
  b = 100
  c = 10

  while a * c < b:
    a = a + 5
    c = c -1
  print("a =",a, "b =", b,"c =",c)
  resp = input("¿Desea ejecutar de nuevo el ejercicio? (Si/No)")
else:
  print("Se terminó el ciclo")

"""**Taller 3. Ciclos repetitivos**

I. Diseña un programa en PYTHON para cada uno de los problemas
que se te plantean.

1. Se necesita un sistema que despliega una tabla de
multiplicar de un número dado por el usuario. ciclo for
"""

num = int(input("Digite el número para mostrarle la tabla de multiplicar: "))
for i in range(11):
  print(i, "x", num, "=", num * i )

"""2. Se necesita un sistema que pida un sueldo de un
trabajador, si el sueldo es mayor a 655000, no tedrá
ninguna bonificación, pero si es menor tiene bonificación
del 4%. Al final se desea saber el total del sueldo con
o sin bonificación. Preguntar si desea ejecutar de nuevo
el programa con el ciclo while.
"""

sueldo = float(input("Ingrese el sueldo del trabajador: "))
bon = round(sueldo * 0.04)
total = bon + sueldo
resp = "si"
while resp == "si" or resp == "SI" or resp == "sí" or resp == "Yes":

  while sueldo > 655000:
   print("No tiene bonificacion")
  else:
   print("Tiene una bonificacion de ", bon, " su sueldo total será ", total)
   resp = input("¿Desea ejecutar de nuevo el ejercicio? (Si/No)")
else:
  print("Se terminó el ejercicio")

"""3. Un maestro necesita un sistema para capturar las
calificaciones de 5 parciales de sus alumnos, después
recapturarlas necesita que se despliegue el promedio,
cuando ya no quiera capturar más alumnos, necesita que
se despliegue el promedio general de todos los alumnos
capturados. Preguntar si desea ejecutar de nuevo el
programa con el ciclo while.
"""

resp = "si"
while resp == "si" or resp == "SI" or resp == "sí" or resp == "Yes":
  calificacion1 = float(input("Digite la calificacion 1: "))
  calificacion2 = float(input("Digite la calificacion 2: "))
  calificacion3 = float(input ("Digite la calificacion 3: "))
  calificacion4 = float(input ("Digite la calificacion 4: "))
  calificacion4 = float(input ("Digite la calificacion 5: "))
  prom = round( (calificacion1 + calificacion2 + calificacion3)/3,2)
  resp = input("¿Desea ejecutar de nuevo el ejercicio? (Si/No)")
  print("El promedio de calificaciones es: ", prom)
else:
  print("El ejercicio ha terminado")

"""4. Crear un bucle que cuente todos los números pares hasta
el 100 ciclo for
"""

for bucle in range(0,101,2):
  print(bucle)

"""5. Haz una tabla de multiplicar utilizando el ciclo for
ciclo for
"""

#Tabla de multiplicar del 3
for i in range(0,11):
  print(i, "x 3 = ", i*3)

"""6. Escribir un programa que pregunte al usuario su edad y
muestre por pantalla todos los años que ha cumplido
(desde 1 hasta su edad). ciclo for
"""

edadUsuario = int(input("Ingrese su edad: "))
for i in range(0,edadUsuario+1):
  print(i)